### ISSUE TITLE
请问默认用户名密码和登录ip

### ISSUE THREAD

**Issue by bonnyandsky** [qughij/openwrt-xiaoyu_xy-c5#4]
我用你编译的openwrt-ramips-mt7621-xiaoyu_xy-c5-squashfs-sysupgrade.bin文件升级我的c5后登录不上去了，192.168.0.1和192.168.1.1我都试过了，不行。请问是不是改了默认地址？

**Comment by qughij** [comment]
默认地址的，没改过。192.168.1.1吧，用户名root，密码password

**Comment by bonnyandsky** [comment]
> 默认地址的，没改过。192.168.1.1吧，用户名root，密码password

那 可能固件有问题，我刷了后进不去192.168.1.1，我后来自己编译了一个c5用的固件，就能用了

**Comment by qughij** [comment]
嗯嗯。我也不知道啊。我编译的是自己可以用的。建议你下次换固件之前先恢复出厂设置一下。
